import { sub } from 'date-fns'


const initialState = [
    {
        id: 1,
        name: 'Nour Eldeen',
        startDate: '20/03/2020',
        phone: '01118025152',
        email: 'noureldeenelqady@gmail.com',
        office: 'Alexandria',
        department: 'Development',
        attendanceProfile: 'Present',
        role: 'Web Developer',
        position: 'Employee',
        directManager: 'Ahmed Tarek',
        workFromHome: false,
        lastModified: sub(new Date(), { minutes: 15 }).toISOString()
    },
    {
        id: 2,
        name: 'Nour Mohamed',
        startDate: '20/05/2020',
        phone: '01118023152',
        email: 'nourmohamed@gmail.com',
        office: 'Alexandria',
        department: 'Business Development',
        attendanceProfile: 'Holiday',
        role: 'HR Head',
        position: 'Employee',
        directManager: 'Ahmed Tarek',
        workFromHome: false,
        lastModified: sub(new Date(), { minutes: 5 }).toISOString()
    },
    {
        id: 3,
        name: 'Ahmed Tarek',
        startDate: '20/05/2019',
        phone: '01116323152',
        email: 'ahmedtarek@gmail.com',
        office: 'Alexandria',
        department: 'Development',
        attendanceProfile: 'On Leave',
        role: 'Development Manager',
        position: 'Manager',
        directManager: '',
        workFromHome: true,
        lastModified: sub(new Date(), { minutes: 10 }).toISOString()
    },
    {
        id: 4,
        name: 'Nour Mohamed',
        startDate: '20/05/2020',
        phone: '01118023152',
        email: 'nourmohamed@gmail.com',
        office: 'Alexandria',
        department: 'Business Development',
        attendanceProfile: 'Absent',
        role: 'HR Head',
        position: 'Employee',
        directManager: 'Ahmed Tarek',
        workFromHome: false,
        lastModified: sub(new Date(), { minutes: 5 }).toISOString()
    },
    {
        id: 5,
        name: 'Sara Khaled Ahmed',
        startDate: '20/05/2020',
        phone: '01118023152',
        email: 'nourmohamed@gmail.com',
        office: 'Alexandria',
        department: 'Business Development',
        attendanceProfile: 'Weekend',
        role: 'HR Head',
        position: 'Employee',
        directManager: 'Ahmed Tarek',
        workFromHome: false,
        lastModified: sub(new Date(), { minutes: 5 }).toISOString()
    },
    {
        id: 6,
        name: 'Nour Eldeen',
        startDate: '20/03/2020',
        phone: '01118025152',
        email: 'noureldeenelqady@gmail.com',
        office: 'Alexandria',
        department: 'Development',
        attendanceProfile: 'Present',
        role: 'Web Developer',
        position: 'Employee',
        directManager: 'Ahmed Tarek',
        workFromHome: false,
        lastModified: sub(new Date(), { minutes: 15 }).toISOString()
    },
    {
        id: 7,
        name: 'Nour Mohamed',
        startDate: '20/05/2020',
        phone: '01118023152',
        email: 'nourmohamed@gmail.com',
        office: 'Alexandria',
        department: 'Business Development',
        attendanceProfile: 'Holiday',
        role: 'HR Head',
        position: 'Employee',
        directManager: 'Ahmed Tarek',
        workFromHome: false,
        lastModified: sub(new Date(), { minutes: 5 }).toISOString()
    },
    {
        id: 8,
        name: 'Ahmed Tarek',
        startDate: '20/05/2019',
        phone: '01116323152',
        email: 'ahmedtarek@gmail.com',
        office: 'Alexandria',
        department: 'Development',
        attendanceProfile: 'On Leave',
        role: 'Development Manager',
        position: 'Manager',
        directManager: '',
        workFromHome: true,
        lastModified: sub(new Date(), { minutes: 10 }).toISOString()
    },
    {
        id: 9,
        name: 'Nour Mohamed',
        startDate: '20/05/2020',
        phone: '01118023152',
        email: 'nourmohamed@gmail.com',
        office: 'Alexandria',
        department: 'Business Development',
        attendanceProfile: 'Absent',
        role: 'HR Head',
        position: 'Employee',
        directManager: 'Ahmed Tarek',
        workFromHome: false,
        lastModified: sub(new Date(), { minutes: 5 }).toISOString()
    },
    {
        id: 10,
        name: 'Sara Khaled Ahmed',
        startDate: '20/05/2020',
        phone: '01118023152',
        email: 'nourmohamed@gmail.com',
        office: 'Alexandria',
        department: 'Business Development',
        attendanceProfile: 'Weekend',
        role: 'HR Head',
        position: 'Employee',
        directManager: 'Ahmed Tarek',
        workFromHome: false,
        lastModified: sub(new Date(), { minutes: 5 }).toISOString()
    },
    {
        id: 11,
        name: 'Nour Eldeen',
        startDate: '20/03/2020',
        phone: '01118025152',
        email: 'noureldeenelqady@gmail.com',
        office: 'Alexandria',
        department: 'Development',
        attendanceProfile: 'Present',
        role: 'Web Developer',
        position: 'Employee',
        directManager: 'Ahmed Tarek',
        workFromHome: false,
        lastModified: sub(new Date(), { minutes: 15 }).toISOString()
    },
    {
        id: 12,
        name: 'Nour Mohamed',
        startDate: '20/05/2020',
        phone: '01118023152',
        email: 'nourmohamed@gmail.com',
        office: 'Alexandria',
        department: 'Business Development',
        attendanceProfile: 'Holiday',
        role: 'HR Head',
        position: 'Employee',
        directManager: 'Ahmed Tarek',
        workFromHome: false,
        lastModified: sub(new Date(), { minutes: 5 }).toISOString()
    },
    {
        id: 13,
        name: 'Ahmed Tarek',
        startDate: '20/05/2019',
        phone: '01116323152',
        email: 'ahmedtarek@gmail.com',
        office: 'Alexandria',
        department: 'Development',
        attendanceProfile: 'On Leave',
        role: 'Development Manager',
        position: 'Manager',
        directManager: '',
        workFromHome: true,
        lastModified: sub(new Date(), { minutes: 10 }).toISOString()
    },
    {
        id: 14,
        name: 'Nour Mohamed',
        startDate: '20/05/2020',
        phone: '01118023152',
        email: 'nourmohamed@gmail.com',
        office: 'Alexandria',
        department: 'Business Development',
        attendanceProfile: 'Absent',
        role: 'HR Head',
        position: 'Employee',
        directManager: 'Ahmed Tarek',
        workFromHome: false,
        lastModified: sub(new Date(), { minutes: 5 }).toISOString()
    },
    {
        id: 15,
        name: 'Sara Khaled Ahmed',
        startDate: '20/05/2020',
        phone: '01118023152',
        email: 'nourmohamed@gmail.com',
        office: 'Alexandria',
        department: 'Business Development',
        attendanceProfile: 'Weekend',
        role: 'HR Head',
        position: 'Employee',
        directManager: 'Ahmed Tarek',
        workFromHome: false,
        lastModified: sub(new Date(), { minutes: 5 }).toISOString()
    },
    {
        id: 16,
        name: 'Nour Eldeen',
        startDate: '20/03/2020',
        phone: '01118025152',
        email: 'noureldeenelqady@gmail.com',
        office: 'Alexandria',
        department: 'Development',
        attendanceProfile: 'Present',
        role: 'Web Developer',
        position: 'Employee',
        directManager: 'Ahmed Tarek',
        workFromHome: false,
        lastModified: sub(new Date(), { minutes: 15 }).toISOString()
    },
    {
        id: 17,
        name: 'Nour Mohamed',
        startDate: '20/05/2020',
        phone: '01118023152',
        email: 'nourmohamed@gmail.com',
        office: 'Alexandria',
        department: 'Business Development',
        attendanceProfile: 'Holiday',
        role: 'HR Head',
        position: 'Employee',
        directManager: 'Ahmed Tarek',
        workFromHome: false,
        lastModified: sub(new Date(), { minutes: 5 }).toISOString()
    },
    {
        id: 18,
        name: 'Ahmed Tarek',
        startDate: '20/05/2019',
        phone: '01116323152',
        email: 'ahmedtarek@gmail.com',
        office: 'Alexandria',
        department: 'Development',
        attendanceProfile: 'On Leave',
        role: 'Development Manager',
        position: 'Manager',
        directManager: '',
        workFromHome: true,
        lastModified: sub(new Date(), { minutes: 10 }).toISOString()
    },
    {
        id: 19,
        name: 'Nour Mohamed',
        startDate: '20/05/2020',
        phone: '01118023152',
        email: 'nourmohamed@gmail.com',
        office: 'Alexandria',
        department: 'Business Development',
        attendanceProfile: 'Absent',
        role: 'HR Head',
        position: 'Employee',
        directManager: 'Ahmed Tarek',
        workFromHome: false,
        lastModified: sub(new Date(), { minutes: 5 }).toISOString()
    },
    {
        id: 20,
        name: 'Sara Khaled Ahmed',
        startDate: '20/05/2020',
        phone: '01118023152',
        email: 'nourmohamed@gmail.com',
        office: 'Alexandria',
        department: 'Business Development',
        attendanceProfile: 'Weekend',
        role: 'HR Head',
        position: 'Employee',
        directManager: 'Ahmed Tarek',
        workFromHome: false,
        lastModified: sub(new Date(), { minutes: 5 }).toISOString()
    },
    {
        id: 21,
        name: 'Nour Eldeen',
        startDate: '20/03/2020',
        phone: '01118025152',
        email: 'noureldeenelqady@gmail.com',
        office: 'Alexandria',
        department: 'Development',
        attendanceProfile: 'Present',
        role: 'Web Developer',
        position: 'Employee',
        directManager: 'Ahmed Tarek',
        workFromHome: false,
        lastModified: sub(new Date(), { minutes: 15 }).toISOString()
    },
    {
        id: 22,
        name: 'Nour Mohamed',
        startDate: '20/05/2020',
        phone: '01118023152',
        email: 'nourmohamed@gmail.com',
        office: 'Alexandria',
        department: 'Business Development',
        attendanceProfile: 'Holiday',
        role: 'HR Head',
        position: 'Employee',
        directManager: 'Ahmed Tarek',
        workFromHome: false,
        lastModified: sub(new Date(), { minutes: 5 }).toISOString()
    },
    {
        id: 23,
        name: 'Ahmed Tarek',
        startDate: '20/05/2019',
        phone: '01116323152',
        email: 'ahmedtarek@gmail.com',
        office: 'Alexandria',
        department: 'Development',
        attendanceProfile: 'On Leave',
        role: 'Development Manager',
        position: 'Manager',
        directManager: '',
        workFromHome: true,
        lastModified: sub(new Date(), { minutes: 10 }).toISOString()
    },
    {
        id: 24,
        name: 'Nour Mohamed',
        startDate: '20/05/2020',
        phone: '01118023152',
        email: 'nourmohamed@gmail.com',
        office: 'Alexandria',
        department: 'Business Development',
        attendanceProfile: 'Absent',
        role: 'HR Head',
        position: 'Employee',
        directManager: 'Ahmed Tarek',
        workFromHome: false,
        lastModified: sub(new Date(), { minutes: 5 }).toISOString()
    },
]

export default initialState;